apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: nginx-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
   - name: nginx-container
     image: nginx:1.14.2
     ports:
      - containerPort: 80
