apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  namespace: default
  name: nginx-pod
  labels:
    zone: prod
    pod-name: nginx-pod
    version: v1
spec:
  restartPolicy: Never # restart if the conatainer fails (Always, Never)
  containers: 
  - name: nginx-container
    image: nginx:1.14.2
    ports:
     - containerPort: 80
