---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace: database
  name: mysql-service
spec:
  type: ClusterIP # there are 3 types (ClusterIP, NodePort, LoadBalancer)
  selector:
    # these lables need to match the replicaSet  (sometimes created by replicaSet or deploymets objects)
    tier: database # Deployment.metadata.labels.tier
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
# Service for webserver (nodePort)
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: frontend-service
spec:
  ports:
    - name: http
      protocol: TCP
      nodePort: 30000 # host port of the worker-node (node)
      port: 80 # host port of the service expose (service)
      targetPort: 80 # container port (pod)
  selector:
    # these lables need to match the replicaSet (sometimes created by replicaSet or deploymets objects)
    tier: frontend # Deployment.metadata.labels.tier
  type: NodePort