---
# Secret clientMysqluser
# for mysql-user echo -n 'mysql-user' | base64 && echo -n 'user-pwd' | base64
apiVersion: v1
kind: Secret
metadata:
  namespace: web
  name: mysql-secret-username
  labels:
    username: mysql-user
data:
  username: bXlzcWwtdXNlcg==
  password: dXNlci1wd2Q=
---
# Secret root
# for root (echo -n 'root-pwd' | base64)
apiVersion: v1
kind: Secret
metadata:
  namespace: web
  name: mysql-secret-root
  labels:
    user: root
type: Opaque
data:
  ROOT_PASSWORD: cm9vdC1wd2Q=