apiVersion: v1
kind: Service
metadata:
  name: nginx-service-clusterip # internal (curl -I serverce ip)
  labels:
    zone: prod
    version: v1
spec:
  type: ClusterIP # there are 3 types (ClusterIP, NodePort, LoadBalancer)
  selector:
    # these lables need to match the replicaSet (sometimes created by replicaSet or deploymets objects)
    zone: prod 
    pod-name: nginx-pod 
    version: v1 
  ports:
    - name: http
      protocol: TCP
      port: 80 # host port of the service expose (service)
      targetPort: 80 # container port (pod)
      
