# deploy a SVC redirecting traffic to "externalName: test.com" from deployment-name "my-dep"
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapi
  name: webapi
spec:
  externalName: test.com
  type: ExternalName
  selector:
    app: my-dep
status:
  loadBalancer: {}
  
  
  # Now using curl from a pod will get the response from "test.com" website
