apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer # external (curl -I loadbalancer)
  labels:
    zone: prod
    version: v1
spec:
  type: LoadBalancer # there are 3 types (ClusterIP, NodePort, LoadBalancer)
  selector:
    zone: prod # 
  ports:
    - name: http
      protocol: TCP
      port: 80 # host port of the service expose (service)
      targetPort: 80 # container port (pod)
      