apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport # external (curl -I node-ip:port)
  labels:
    zone: prod
    version: v1
spec:
  type: NodePort # there are 3 types (ClusterIP, NodePort, LoadBalancer)
  selector:
    zone: prod # 
  ports:
    - name: http
      protocol: TCP
      nodePort: 30000 # host port of the worker-node (node)
      port: 80 # host port of the service expose (service)
      targetPort: 80 # container port (pod)


