apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-https
spec:
  # pod with multiple containers
  containers: 
  - image: linuxacademycontent/fortune
    name: html-web # this is the container (1) 'html-web' 
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: config-https
          key: sleep-interval
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server # this is the container (2) 'web-server' 
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    ports:
    - containerPort: 80
    - containerPort: 443
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: config-https
      items:
      - key: my-nginx-config.conf
        path: https.conf
  - name: certs
    secret:
      secretName: example-https