apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    zone: prod
    version: v1
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      zone: prod # this is the label need to that match the pod's labels (spec.template.labels)
      pod-name: nginx-pod # this is the label need to that match the pod's labels (spec.template.labels)
      version: v1 # this is the label need to that match the pod's labels (spec.template.labels)
  template:
    metadata:
      labels:
        zone: prod # this lablel will be used by the replicaset (spec.selector.matchLabels)
        pod-name: nginx-pod # this lablel will be used by the replicaset (spec.selector.matchLabels)
        version: v1 # this lablel will be used by the replicaset (spec.selector.matchLabels)
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80